export const MARKET_DATA_LOADING = "MARKET_DATA_LOADING";
export const MARKET_DATA_SUCCESS = "MARKET_DATA_SUCCESS";
export const MARKET_DATA_FAIL = "MARKET_DATA_FAIL";

export const REDDIT_DATA_LOADING = "REDDIT_DATA_LOADING";
export const REDDIT_DATA_SUCCESS = "REDDIT_DATA_SUCCESS";
export const REDDIT_DATA_FAIL = "REDDIT_DATA_FAIL";
